[package]
name = "dialectical-payments-meta"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies.dialectical-payments]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.64.0"
default-features = false
